server:
  port: 8082

logging:
  level:
    root: info

spring:
  datasource:
    url: jdbc:mysql://192.168.100.54:3306/user?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: test
    password: Meihao100@bfbd
    driver-class-name: com.mysql.cj.jdbc.Driver

  kafka:
    bootstrap-servers: localhost:9092  # 多个使用`,`隔开
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      retries: 0 # 失败重试次数
      batch-size: 16384
      buffer-memory: 33554432
      acks: -1 # 取值 all, -1, 0, 1
      compression-type: gzip #生产者生产消息启用的算法
    consumer:
      enable-auto-commit: false #手动提交
      auto-commit-interval: 5000
      group-id: elong
      auto-offset-reset: earliest # 消费offset取值earliest,latest,none（默认：latest）
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      max-poll-records: 10  #最大拉取数
    listener:
      ack-mode: MANUAL   #手动模式 其实还是批量按最大拉去数批量提交
      poll-timeout: 100
      ack-time: 100
      concurrency: 10 #最大处理线程数据


  redis:
    port: 6379
    host: 127.0.0.1
    database: 0
    timeout: 2000


# 自定义producer topic
kafka:
  producer:
    topic: erlong