server:
  port: 80

logging:
  level:
    root: info

spring:
  datasource:
    url: jdbc:mysql://192.168.100.54:3306/user?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: test
    password: Meihao100@bfbd
    driver-class-name: com.mysql.cj.jdbc.Driver