server:
  port: 8081

logging:
  level:
    root: info

spring:
  datasource:
    url: jdbc:mysql://192.168.100.54:3306/user?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: test
    password: Meihao100@bfbd
    driver-class-name: com.mysql.cj.jdbc.Driver

  kafka:
    bootstrap-servers: localhost:9092  # 多个使用`,`隔开
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      retries: 0 # 失败重试次数
      batch-size: 16384
      buffer-memory: 33554432
      acks: -1 # 取值 all, -1, 0, 1
    consumer:
      enable-auto-commit: true
      auto-commit-interval: 5000
      group-id: group-test
      auto-offset-reset: earliest # 消费offset取值earliest,latest,none（默认：latest）
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

  redis:
    port: 6379
    host: 127.0.0.1
    database: 0
    timeout: 2000


# 自定义producer topic
kafka:
  producer:
    topic: erlong